// GitHub Trending data layer.
//
// Architecture (v2 — static export):
// - lib/generated/stars.ts: primary data source, committed by GitHub Actions daily.
//   Contains AI-evaluated projects with pre-filled wow/useful/easy scores.
// - lib/generated/lastSnapshot.ts: star counts from the previous Actions run,
//   committed by Actions. Used to compute the delta.
// - lib/data/stars.ts: hand-curated fallback, used when generated data is empty
//   or all API calls fail.
// - Live star counts: fetched from GitHub API at build time to keep totalStars
//   fresh. deltaStars = current total - previous snapshot total.
//
// Resolved at build time (static export). Rebuild via GitHub Actions to refresh.
// Git is the snapshot store: each Actions run commits the current star counts
// as the next run's "previous snapshot", so we can diff run-over-run.

import type { StarProject } from "@/lib/data/types";
import { starFallback } from "@/lib/data/stars";
import { generatedStars } from "@/lib/generated/stars";
import { lastSnapshot } from "@/lib/generated/lastSnapshot";
import { toStarBoardProject, type StarBoardProject } from "@/lib/logic/projects";

export interface TrendingResult {
  fetchedAt: string;
  projects: StarBoardProject[];
  source: "live" | "generated" | "fallback";
}

// ── Live star fetching ────────────────────────────────────────────────────────

interface RepoStats {
  repo: string;
  stargazers_count: number;
  language: string | null;
  description: string | null;
}

async function fetchRepoStats(repo: string): Promise<RepoStats | null> {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "idea-coding",
  };
  const token = process.env.GITHUB_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;

  try {
    const res = await fetch(`https://api.github.com/repos/${repo}`, { headers });
    if (!res.ok) return null;
    const data = (await res.json()) as {
      stargazers_count: number;
      language: string | null;
      description: string | null;
    };
    return {
      repo,
      stargazers_count: data.stargazers_count,
      language: data.language,
      description: data.description,
    };
  } catch {
    return null;
  }
}

// ── Compose projects ──────────────────────────────────────────────────────────
// Merge live stats into the generated/curated star project list:
// - Use the generated/curated project's wow/useful/easy/tagline/mvp
// - Overwrite tagline with live GitHub description if available
// - Overwrite totalStars / deltaStars with live data
function composeProjects(allStars: StarProject[], liveStats: RepoStats[]): StarProject[] {
  const statsMap = new Map(liveStats.map((s) => [s.repo, s]));

  const composed = allStars.map((project) => {
    const stats = statsMap.get(project.repo);
    const totalStars = stats?.stargazers_count ?? project.totalStars ?? 0;

    // deltaStars = current total - previous snapshot's total
    const prevCount = lastSnapshot.counts[project.repo];
    const deltaStars =
      prevCount != null
        ? Math.max(0, totalStars - prevCount)
        : project.deltaStars ?? 0;

    return {
      ...project,
      totalStars,
      deltaStars,
      tagline: stats?.description || project.tagline,
      language: stats?.language || project.language,
    } satisfies StarProject;
  });

  // Rank by delta (desc). Tiebreak by total stars.
  composed.sort((a, b) => b.deltaStars - a.deltaStars || b.totalStars - a.totalStars);
  composed.forEach((p, i) => {
    p.trendingRank = i + 1;
  });

  return composed;
}

// ── Main export ───────────────────────────────────────────────────────────────

export async function fetchTrending(): Promise<TrendingResult> {
  const fetchedAt = new Date().toISOString();

  // Primary data source: generated by Actions. Fall back to hand-written.
  const allStars = generatedStars.length > 0 ? generatedStars : starFallback;
  const hasGenerated = generatedStars.length > 0;

  if (allStars.length === 0) {
    return { fetchedAt, projects: [], source: "fallback" };
  }

  // Fetch live star counts for all candidate repos concurrently.
  const stats = await Promise.all(
    allStars.map((p) => fetchRepoStats(p.repo).catch(() => null))
  );
  const ok = stats.filter((s): s is RepoStats => s !== null);

  // If we got nothing useful, fall back to static data (no live star refresh).
  if (ok.length === 0) {
    return {
      fetchedAt,
      projects: allStars.map((p, i) => toStarBoardProject(p, i)),
      source: "fallback",
    };
  }

  const projects = composeProjects(allStars, ok);

  const source: TrendingResult["source"] =
    hasGenerated ? "live" : "fallback";

  return { fetchedAt, projects: projects.map((p, i) => toStarBoardProject(p, i)), source };
}
